#spring.profiles.active=dev
#spring.config.additional-location=file:D:/Projects/Full Stack Projects/CustomerPortal/configurations/

spring.config.import=optional:file:/Users/prayashdas/Desktop/eRevMax-Customer-Portal/configurations/application-dev.yml